---
- name: Configurar Monitoramento Avancado Wazuh
  hosts: all
  gather_facts: no
  tasks:
    - name: Atualizar configuracao do Wazuh (Sem a linha config_profile)
      ansible.windows.win_copy:
        dest: 'C:\Program Files (x86)\ossec-agent\ossec.conf'
        content: |
          <ossec_config>
            <client>
              <server>
                <address>192.168.1.232</address>
                <port>1514</port>
                <protocol>tcp</protocol>
              </server>
            </client>

            <localfile>
              <location>Microsoft-Windows-Sysmon/Operational</location>
              <log_format>eventchannel</log_format>
            </localfile>
            <localfile>
              <location>Security</location>
              <log_format>eventchannel</log_format>
            </localfile>
            <localfile>
              <location>System</location>
              <log_format>eventchannel</log_format>
            </localfile>
            <localfile>
              <location>Application</location>
              <log_format>eventchannel</log_format>
            </localfile>
            <localfile>
              <location>Microsoft-Windows-Partition/Diagnostic</location>
              <log_format>eventchannel</log_format>
            </localfile>
          </ossec_config>

    - name: Reiniciar servico Wazuh
      ansible.windows.win_service:
        name: Wazuh
        state: restarted
