  ---
- name: Auditoria de Apps - Sincronizando com Zabbix
  hosts: all
  gather_facts: no

  vars:
    zabbix_url: "http://192.168.1.14:8080/api_jsonrpc.php"
    zabbix_token: "3626f0dcb324a8ab4c948ea90dccb7c6a934a03e01ea3cc386eae6eca61e3dd8"

  tasks:
    - name: 1. Verificar atualizações no Windows via Winget
      ansible.windows.win_shell: |
        $list = winget upgrade --include-unknown | Select-String "available"
        if ($list) { $list | Out-String } else { "Tudo atualizado" }
      register: winget_out
      ignore_errors: yes

    - name: 2. Buscar HostID no Zabbix pelo IP da Interface
      delegate_to: localhost
      ansible.builtin.uri:
        url: "{{ zabbix_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostinterface.get"
          params:
            filter:
              ip: "{{ inventory_hostname }}"
            output: ["hostid"]
          auth: "{{ zabbix_token }}"
          id: 1
      register: zabbix_interface_search

    - name: 3. Buscar Nome do Host usando o HostID encontrado
      delegate_to: localhost
      ansible.builtin.uri:
        url: "{{ zabbix_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            hostids: "{{ zabbix_interface_search.json.result[0].hostid }}"
            output: ["host"]
          auth: "{{ zabbix_token }}"
          id: 1
      register: zabbix_host_search
      when: zabbix_interface_search.json.result | length > 0

    - name: 4. Definir nome real do host
      ansible.builtin.set_fact:
        zabbix_real_name: "{{ zabbix_host_search.json.result[0].host | default('') }}"
      when: zabbix_host_search.json is defined

    - name: 5. DEBUG - Mostrar o nome encontrado
      ansible.builtin.debug:
        msg: "IP {{ inventory_hostname }} mapeado para o Host Zabbix: {{ zabbix_real_name }}"
      when: zabbix_real_name != ""

    - name: 6. Enviar dados para o Zabbix
      delegate_to: localhost
      ansible.builtin.uri:
        url: "{{ zabbix_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "history.push"
          params:
            - host: "{{ zabbix_real_name }}"
              key: "apps.updates.list"
              value: "{{ winget_out.stdout | default('Sem dados') }}"
          auth: "{{ zabbix_token }}"
          id: 1
      when: zabbix_real_name != ""
