---
- name: Relatório de Softwares Instalados
  hosts: all
  gather_facts: no
  tasks:
    - name: Coletar lista de programas via PowerShell
      ansible.windows.win_shell: |
        Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | 
        Select-Object DisplayName, DisplayVersion | 
        Where-Object { $_.DisplayName -ne $null } | 
        Sort-Object DisplayName | 
        Format-Table -AutoSize
      register: resultado_apps

    - name: Exibir lista de programas no log do AWX
      debug:
        msg: "{{ resultado_apps.stdout_lines }}"

    - name: Enviar lista para o Inventario do Zabbix
      delegate_to: localhost
      community.zabbix.zabbix_host:
        server_url: "http://192.168.1.14"
        login_user: "Admin"               # COLOQUE SEU USUARIO AQUI (Case Sensitive)
        login_password: "sua_senha_aqui"  # COLOQUE SUA SENHA AQUI
        host_name: "{{ inventory_hostname }}"
        inventory_mode: manual
        inventory:
          # O Ansible vai colar a tabela do PowerShell dentro deste campo no Zabbix
          software_full: "{{ resultado_apps.stdout }}"
      ignore_errors: yes
