---
- name: Deploy Top CPU Zabbix
  hosts: all
  gather_facts: no

  tasks:

    - name: Verifica Agent 2
      win_stat:
        path: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
      register: agent2

    - name: Define Agent 2
      set_fact:
        zabbix_conf: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
        zabbix_dir: 'C:\Program Files\Zabbix Agent 2\scripts'
        zabbix_service: 'Zabbix Agent 2'
      when: agent2.stat.exists

    - name: Define Agent Classico
      set_fact:
        zabbix_conf: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'
        zabbix_dir: 'C:\Program Files\Zabbix Agent\scripts'
        zabbix_service: 'Zabbix Agent'
      when: not agent2.stat.exists

    - name: Criar pasta scripts
      win_file:
        path: "{{ zabbix_dir }}"
        state: directory

    - name: Copiar PS1
      win_copy:
        src: files/top_cpu.ps1
        dest: "{{ zabbix_dir }}\\top_cpu.ps1"

    - name: Adicionar UserParameter
      win_shell: |
        $linha = 'UserParameter=custom.topcpu,powershell.exe -ExecutionPolicy Bypass -File "{{ zabbix_dir }}\top_cpu.ps1"'

        if (-not (Select-String -Path "{{ zabbix_conf }}" -Pattern "custom.topcpu" -Quiet)) {
            Add-Content -Path "{{ zabbix_conf }}" -Value $linha
        }

    - name: Reiniciar agente
      win_service:
        name: "{{ zabbix_service }}"
        state: restarted
