---
- name: Verificar Atualizações (Apenas Listar)
  hosts: all
  gather_facts: no
  tasks:
    - name: Consultar atualizações pendentes via Winget
      ansible.windows.win_shell: |
        # Sem comandos de reset! Apenas a busca direta e limpa.
        # --disable-interactivity: Oculta as barras de progresso e evita travamentos no Ansible
        winget upgrade --accept-package-agreements --accept-source-agreements --disable-interactivity | Out-String
      register: winget_result
      failed_when: false 

    - name: Exibir lista no log do AWX
      debug:
        msg: "{{ winget_result.stdout_lines }}"

    - name: Enviar lista para o campo Notas do Zabbix
      delegate_to: localhost
      ansible.builtin.uri:
        url: "http://192.168.1.14/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer cfbf448e275112250c7fe06ef9e84505fe5ea46b880cc3e46c7671267d5cb432"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.update"
          params:
            hostid: "{{ zbx_hostid }}"
            inventory_mode: 0
            inventory:
              notes: "ATUALIZAÇÕES DISPONÍVEIS:\n{{ winget_result.stdout }}"
          id: 1
      ignore_errors: yes
